### ISSUE TITLE
a few reports from initial usage

### ISSUE THREAD

**Issue by i3d** [smilhey/cabinet.nvim#1]
This section seems a bit of problematic

```
return {
    "smilhey/cabinet", 
    config = function () 
        local cabinet = require("cabinet")
        cabinet:setup()
    end
}
```

The package name probably is missing `.nvim`. The setup also seems require a non-nil table, or it will error out.

Also, another thing maybe to improve is that if there is only one drawer, delete it will result in error.

**Comment by smilhey** [comment]
Hello, the last commit should address the issues with setup being called without argument and deleting the last drawer. Tell me if you still experienc the issue. What makes you think the package name is missing nvim ?

**Comment by unphased** [comment]
I just made a PR to address the issue. @smilhey you renamed your repo from `cabinet` to `cabinet.nvim` so now lazy will fail to fetch it if you use the snippet here, because it is not using the new github repo name

**Comment by smilhey** [comment]
Oh yeah I thought @i3d was talking about the module name. I also changed it in the config example
